import pg from 'pg';
import type { TelegramUser } from './telegram-auth.js';
const {Pool}=pg;const connectionString=process.env.DATABASE_URL;export const db=connectionString?new Pool({connectionString,ssl:{rejectUnauthorized:false},max:5}):null;
export type AppUser={id:string;telegram_user_id:string;telegram_username:string|null;first_name:string;last_name:string|null;language_code:string|null;photo_url:string|null};export type PropertyStatus='draft'|'published'|'archived';export type Property={id:string;owner_id:string;status:PropertyStatus;title:string;city:string;address:string;description:string;price_per_night:string;currency:'BYN';max_guests:number;amenities:string[];house_rules:string;check_in_time:string|null;check_out_time:string|null;created_at:string;updated_at:string};export type PropertyInput={title:string;city:string;address:string;description?:string;price_per_night:number;max_guests:number;amenities?:string[];house_rules?:string;check_in_time?:string|null;check_out_time?:string|null};export type PropertyPhoto={id:string;property_id:string;storage_path:string;sort_order:number;is_cover:boolean;created_at:string};export type CatalogProperty=Property&{cover_path:string|null};
function needDb(){if(!db)throw new Error('DATABASE_URL is not configured');return db}
export async function upsertTelegramUser(u:TelegramUser):Promise<AppUser>{const r=await needDb().query<AppUser>(`insert into public.users (telegram_user_id,telegram_username,first_name,last_name,language_code,photo_url,updated_at) values ($1,$2,$3,$4,$5,$6,now()) on conflict (telegram_user_id) do update set telegram_username=excluded.telegram_username,first_name=excluded.first_name,last_name=excluded.last_name,language_code=excluded.language_code,photo_url=excluded.photo_url,updated_at=now() returning id,telegram_user_id::text,telegram_username,first_name,last_name,language_code,photo_url`,[u.id,u.username??null,u.first_name,u.last_name??null,u.language_code??null,u.photo_url??null]);return r.rows[0]}
export async function createProperty(o:string,i:PropertyInput):Promise<Property>{return(await needDb().query<Property>(`insert into public.properties (owner_id,title,city,address,description,price_per_night,max_guests,amenities,house_rules,check_in_time,check_out_time) values ($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10,$11) returning *`,[o,i.title,i.city,i.address,i.description??'',i.price_per_night,i.max_guests,JSON.stringify(i.amenities??[]),i.house_rules??'',i.check_in_time??null,i.check_out_time??null])).rows[0]}
export async function listOwnerProperties(o:string){return(await needDb().query<Property>(`select * from public.properties where owner_id=$1 order by updated_at desc`,[o])).rows}export async function getOwnerProperty(o:string,id:string){return(await needDb().query<Property>(`select * from public.properties where id=$1 and owner_id=$2 limit 1`,[id,o])).rows[0]??null}export async function updateOwnerProperty(o:string,id:string,i:PropertyInput){return(await needDb().query<Property>(`update public.properties set title=$3,city=$4,address=$5,description=$6,price_per_night=$7,max_guests=$8,amenities=$9::jsonb,house_rules=$10,check_in_time=$11,check_out_time=$12,updated_at=now() where id=$1 and owner_id=$2 returning *`,[id,o,i.title,i.city,i.address,i.description??'',i.price_per_night,i.max_guests,JSON.stringify(i.amenities??[]),i.house_rules??'',i.check_in_time??null,i.check_out_time??null])).rows[0]??null}
export async function setPropertyStatus(o:string,id:string,status:'draft'|'published'):Promise<Property|null>{return(await needDb().query<Property>(`update public.properties set status=$3,updated_at=now() where id=$1 and owner_id=$2 returning *`,[id,o,status])).rows[0]??null}
export async function listPublishedProperties(city?:string,guests?:number):Promise<CatalogProperty[]>{const values:unknown[]=[];const where=[`p.status='published'`];if(city?.trim()){values.push('%'+city.trim()+'%');where.push(`p.city ilike $${values.length}`)}if(guests&&Number.isInteger(guests)&&guests>0){values.push(guests);where.push(`p.max_guests >= $${values.length}`)}return(await needDb().query<CatalogProperty>(`select p.*,coalesce((select ph.storage_path from public.property_photos ph where ph.property_id=p.id order by ph.is_cover desc,ph.sort_order,ph.created_at limit 1),null) cover_path from public.properties p where ${where.join(' and ')} order by p.updated_at desc limit 100`,values)).rows}
export async function getPublishedProperty(id:string):Promise<Property|null>{return(await needDb().query<Property>(`select * from public.properties where id=$1 and status='published' limit 1`,[id])).rows[0]??null}
export async function listPublishedPropertyPhotos(id:string):Promise<PropertyPhoto[]>{return(await needDb().query<PropertyPhoto>(`select ph.* from public.property_photos ph join public.properties p on p.id=ph.property_id where ph.property_id=$1 and p.status='published' order by ph.sort_order,ph.created_at`,[id])).rows}
export async function listPropertyPhotos(o:string,id:string){return(await needDb().query<PropertyPhoto>(`select ph.* from public.property_photos ph join public.properties p on p.id=ph.property_id where ph.property_id=$1 and p.owner_id=$2 order by ph.sort_order,ph.created_at`,[id,o])).rows}export async function addPropertyPhoto(o:string,id:string,path:string){return(await needDb().query<PropertyPhoto>(`insert into public.property_photos(property_id,storage_path,sort_order,is_cover) select p.id,$3,coalesce((select max(sort_order)+1 from public.property_photos where property_id=p.id),0),not exists(select 1 from public.property_photos where property_id=p.id) from public.properties p where p.id=$1 and p.owner_id=$2 returning *`,[id,o,path])).rows[0]??null}
export async function setCoverPhoto(o:string,pid:string,photoId:string){const c=await needDb().connect();try{await c.query('begin');const owns=await c.query(`select 1 from public.property_photos ph join public.properties p on p.id=ph.property_id where ph.id=$1 and ph.property_id=$2 and p.owner_id=$3`,[photoId,pid,o]);if(!owns.rowCount){await c.query('rollback');return false}await c.query(`update public.property_photos set is_cover=false where property_id=$1`,[pid]);await c.query(`update public.property_photos set is_cover=true where id=$1 and property_id=$2`,[photoId,pid]);await c.query('commit');return true}catch(e){await c.query('rollback');throw e}finally{c.release()}}
export async function removePropertyPhoto(o:string,pid:string,photoId:string):Promise<{storage_path:string}|null>{const c=await needDb().connect();try{await c.query('begin');const r=await c.query<{storage_path:string;is_cover:boolean}>(`delete from public.property_photos ph using public.properties p where ph.id=$1 and ph.property_id=$2 and p.id=ph.property_id and p.owner_id=$3 returning ph.storage_path,ph.is_cover`,[photoId,pid,o]);if(!r.rows[0]){await c.query('rollback');return null}await c.query(`with ranked as(select id,row_number() over(order by sort_order,created_at)-1 n from public.property_photos where property_id=$1) update public.property_photos ph set sort_order=ranked.n from ranked where ph.id=ranked.id`,[pid]);if(r.rows[0].is_cover)await c.query(`update public.property_photos set is_cover=true where id=(select id from public.property_photos where property_id=$1 order by sort_order,created_at limit 1)`,[pid]);await c.query('commit');return{storage_path:r.rows[0].storage_path}}catch(e){await c.query('rollback');throw e}finally{c.release()}}
export async function movePropertyPhoto(o:string,pid:string,photoId:string,direction:'up'|'down'){const c=await needDb().connect();try{await c.query('begin');const photos=(await c.query<{id:string;sort_order:number}>(`select ph.id,ph.sort_order from public.property_photos ph join public.properties p on p.id=ph.property_id where ph.property_id=$1 and p.owner_id=$2 order by ph.sort_order,ph.created_at for update of ph`,[pid,o])).rows;const i=photos.findIndex(x=>x.id===photoId),j=direction==='up'?i-1:i+1;if(i<0||j<0||j>=photos.length){await c.query('rollback');return false}await c.query(`update public.property_photos set sort_order=case id when $1 then $4 when $2 then $3 end where id in($1,$2)`,[photos[i].id,photos[j].id,photos[i].sort_order,photos[j].sort_order]);await c.query('commit');return true}catch(e){await c.query('rollback');throw e}finally{c.release()}}
export async function databaseHealth(){if(!db)return false;await db.query('select 1');return true}